export const SET_USER = "SET_USER";

export const SET_LOADING_STATUS = "SET_LOADING_STATUS";

export const GET_ARTICLES = "GET_ARTICLES";


export const TOGGLE_COMMENT_INPUT = "TOGGLE_COMMENT_INPUT";



export const ADD_COMMENT = "ADD_COMMENT";
